# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
server.port=8080
spring.application.name=api-gateway

spring.cloud.gateway.server.webflux.routes[0].id=customer-service-route
spring.cloud.gateway.server.webflux.routes[0].uri=lb\://customer-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path\=/api/customers/**

spring.cloud.gateway.server.webflux.routes[1].id=supplier-service-route
spring.cloud.gateway.server.webflux.routes[1].uri=lb\://supplier-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path\=/api/suppliers/**

spring.cloud.gateway.server.webflux.routes[2].id=inventory-service-route
spring.cloud.gateway.server.webflux.routes[2].uri=lb\://inventory-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path\=/api/inventory/**

spring.cloud.gateway.server.webflux.routes[3].id=order-service-route
spring.cloud.gateway.server.webflux.routes[3].uri=lb\://order-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path\=/api/orders/**

spring.cloud.gateway.server.webflux.routes[4].id=reporting-service-route
spring.cloud.gateway.server.webflux.routes[4].uri=lb\://reporting-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path\=/api/reporting/**

spring.cloud.gateway.server.webflux.routes[5].id=payment-service-route
spring.cloud.gateway.server.webflux.routes[5].uri=lb\://payment-service
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path\=/api/payment/**

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http\://localhost\:8090/realms/spring-boot-realm/protocol/openid-connect/certs
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.default-zone=http\://localhost\:8761/eureka/
eureka.instance.prefer-ip-address=true
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG
