server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: customer-service-route
            uri: lb://customer-service
            predicates:
            - Path=/api/customers/**
          - id: supplier-service-route
            uri: lb://supplier-service
            predicates:
            - Path=/api/suppliers/**
          - id: inventory-service-route
            uri: lb://inventory-service
            predicates:
            - Path=/api/inventory/**
            - Path=/api/categories/**
          - id: order-service-route
            uri: lb://order-service
            predicates:
            - Path=/api/orders/**
          - id: reporting-service-route
            uri: lb://reporting-service
            predicates:
            - Path=/api/reporting/**
          - id: payment-service-route
            uri: lb://payment-service
            predicates:
            - Path=/api/payment/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8090/realms/spring-boot-realm/protocol/openid-connect/certs
      # BẮT ĐẦU PHẦN CẤU HÌNH CLIENT BỔ SUNG
      client:
        registration:
          keycloak:
            client-id: apigateway-client 
            client-secret: lYPJVwtldNdB5BTRsLRDLbY9e1BV28vR # Secret của bạn
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://localhost:8090/realms/spring-boot-realm
      # KẾT THÚC PHẦN CẤU HÌNH CLIENT BỔ SUNG
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
    reactor:
      netty:
        http:
          client: DEBUG